### PR TITLE
Improve rsc syntax highlighting

### PR DESCRIPTION
**Pull request by dkearns**
Here's a couple of small improvements.

- escape sequence highlighting
- and or in operator highlighting

Is it intentional that rscSpecial is included in rscString?

### CODE REVIEW

**Review by zainin — COMMENTED** [review]
Thanks for the changes.

Honestly, at this point I'm not sure why rscSpecial was included in rscString - but it feels like it shouldn't be.
Let me know what you think is best and we'll go with that.

**Comment by dkearns** [comment]
Ok, I removed the Special group from String and added line continuations.

String should probably highlight interpolated expressions at some stage but it's not causing any problems at the moment so I'll leave it.

I have some other small changes but I might not get to them until the end of next week so it might be better to consider this done for the moment if you're happy with it?

I renamed the filetype from `rsc` to `routeros` but it would be worth double checking I didn't miss anything.

I added you as maintainer of the ftplugin.  It's very basic so I doubt there will be any maintenance but you can use my name if you don't want to take that on as well.

I think Bram also requires, or at least prefers, to have a proper maintainer contact in the header even though we're now also using CODEOWNERS.  If you don't want to add an email address maybe you could create a vim-routeros project on GH to host it?

Thanks.

**Comment by zainin** [comment]
Thanks again for your tweaks.

I don't mind if we leave me as the maintainer for the ftplugin.

I'll add my contact to the header (right after this PR is merged), I wasn't really sure if it's required or not.

Overall I'm good with the code as it is.
Should we merge this now and continue with the original PR in the vim repo, or wait until you can add the other changes?

**Comment by dkearns** [comment]
If you're happy I reckon we should get it in now. Thanks.

**Pull request merged**
